"""
gi_lookup.py — fuzzy name search over the bundled Foster-Powell/Holt/
Brand-Miller glycemic index reference table (see user-manual.md footnote 8
and gi_data.json, generated by scripts/build_gi_data.py).

Used by the Food Cache "Annotate" page's GI lookup section: given a food's
name, return every plausibly-matching table entry (not just the single best
guess) so the user picks the right one themselves, tagged by which subject
population it was measured in — "normal" (Table A1) or "impaired" (Table
A2, glucose-intolerant/diabetic subjects, small-n, or high-variance
studies). GI values are always on the glucose-referenced scale (GI
Glucose=100), matching the scale numa uses everywhere else — see
usda_nutrients docstrings and user-manual.md section N.

Deliberately does NOT surface glycemic load: numa already derives GL live
from a food's own cached carbohydrate content and the amount consumed (see
numa_app.services.glycemic_load), which is more accurate for that specific
cached food than rescaling the study's own tested-product GL would be.

Docs: README-numa-documentation.md, Architecture: "gi_lookup.py — Foster-Powell GI table lookup"
"""
from __future__ import annotations

import difflib
import json
import re
from pathlib import Path

_DATA_PATH = Path(__file__).parent / "gi_data.json"

_data_cache: dict[str, list[dict]] | None = None


def _data() -> dict[str, list[dict]]:
    global _data_cache
    if _data_cache is None:
        if _DATA_PATH.exists():
            _data_cache = json.loads(_DATA_PATH.read_text(encoding="utf-8"))
        else:
            _data_cache = {"normal": [], "impaired": []}
    return _data_cache


def _normalize(name: str) -> str:
    name = name.lower()
    name = re.sub(r"[^a-z0-9]+", " ", name)
    return re.sub(r"\s+", " ", name).strip()


def _score(query_norm: str, entry_norm: str) -> float:
    if not query_norm or not entry_norm:
        return 0.0
    if query_norm == entry_norm:
        return 1.0
    if query_norm in entry_norm or entry_norm in query_norm:
        return 0.9
    return difflib.SequenceMatcher(None, query_norm, entry_norm).ratio()


def search(query: str, population: str = "both", limit: int = 8, cutoff: float = 0.5) -> list[dict]:
    """Return up to `limit` candidate table entries for `query`, ranked by
    name-match quality (best first). `population` is "normal", "impaired",
    or "both". Each result: {name, gi_glucose, population, category, ref,
    score}. [] if the data file hasn't been generated yet (see
    scripts/build_gi_data.py) or nothing scored above `cutoff`."""
    query_norm = _normalize(query)
    if not query_norm:
        return []

    data = _data()
    pools = ([data.get("normal", []), data.get("impaired", [])] if population == "both"
             else [data.get(population, [])])

    scored = []
    for pool in pools:
        for entry in pool:
            s = _score(query_norm, _normalize(entry["name"]))
            if s >= cutoff:
                scored.append({**entry, "score": s})

    scored.sort(key=lambda e: e["score"], reverse=True)
    return scored[:limit]
