"""
gi_lookup.py — fuzzy name search over the bundled Atkinson/Brand-Miller
glycemic index reference table (see user-manual.md footnote 8 and
gi_data.json, generated by scripts/build_gi_data.py).

Used by the Food Cache "Annotate" page's GI lookup section: given a food's
name, return every plausibly-matching table entry (not just the single best
guess) so the user picks the right one themselves. GI values are always on
the glucose-referenced scale (GI Glucose=100), matching the scale numa uses
everywhere else — see usda_nutrients docstrings and user-manual.md section N.

Two tables can supply entries, and which one is in use depends on the install:

* The **bundled** table (`gi_data.json`) is the 2008 edition, which is
  Creative Commons licensed and so may ship with NuMa. Every install has it.
* An **optional local** table (`gi_data_local.json`) built by the user from the
  2021 edition, which is published under a licence permitting text and data
  mining but forbidding redistribution — so NuMa ships the parser for it
  (numa_app/services/gi_table_build.py, run from Settings) and never the
  result. When present it supersedes the bundled table, since the builder folds
  the 2008 rows 2021 does not cover into its own output.

Each result therefore reports which edition it came from and, for 2021 rows,
the year the study was run — a 1998 value for a commercial product that has
been reformulated since is worth seeing before picking it. 2008 rows have no
year: that extraction never captured one, and the edition is not a measurement
date, so the picker shows the year as unrecorded rather than guessing.

Population is each row's own subject group, not a property of which published
table it sits in — the 2021 tables are split by ISO 26642:2010 method
compliance instead, and most of the non-compliant table was still measured in
normal-tolerance subjects. Rows whose subject group the source leaves
unstated are returned for either population rather than withheld from both.

Deliberately does NOT surface glycemic load: numa already derives GL live
from a food's own cached carbohydrate content and the amount consumed (see
numa_app.services.glycemic_load), which is more accurate for that specific
cached food than rescaling the study's own tested-product GL would be.

Docs: README-numa-documentation.md, Architecture: "gi_lookup.py — Foster-Powell GI table lookup"
"""
from __future__ import annotations

import datetime
import difflib
import json
import re
from pathlib import Path

_DATA_PATH = Path(__file__).parent / "gi_data.json"
_LOCAL_NAME = "gi_data_local.json"

_data_cache: dict[str, list[dict]] | None = None


def _local_paths() -> list[Path]:
    """Where a user-built 2021 table may sit, in priority order.

    The data directory comes first so a packaged install — where the program
    lives in a read-only bundle the user cannot write into — can still take an
    upgrade. Beside the module is the convenient spot in a dev checkout, and is
    where scripts/build_gi_data.py writes.
    """
    paths = [Path(__file__).parent / _LOCAL_NAME]
    try:
        import platform_utils
        paths.insert(0, platform_utils.get_data_dir() / _LOCAL_NAME)
    except Exception:
        pass            # data dir unavailable: the bundled table still works
    return paths


def user_table_path() -> Path:
    """Where the Settings page's Build button writes a 2021 table: the first
    (highest-priority) of _local_paths(), i.e. the user's data directory."""
    return _local_paths()[0]


def reload() -> None:
    """Drop the in-memory table so the next lookup re-reads whichever file is
    now active. The table is otherwise loaded once per app run, so a build (or
    a deletion) would not be seen until restart."""
    global _data_cache
    _data_cache = None


def active_table_path() -> Path | None:
    """The table actually in use: a locally-built 2021 one if the user has made
    it, otherwise the bundled 2008 baseline. None if neither exists."""
    for path in _local_paths():
        if path.exists():
            return path
    return _DATA_PATH if _DATA_PATH.exists() else None


def local_table_candidates() -> list[str]:
    """Every path a user-built 2021 table would be picked up from, in the order
    checked — so Settings can say where to put one when none is present."""
    return [str(path) for path in _local_paths()]


def active_table_info() -> dict:
    """Describe the table actually in use, for display in the web UI.

    Which edition answers a GI lookup is an install-level fact the user
    otherwise cannot see: a locally-built 2021 table supersedes the bundled
    2008 one silently, and deleting or renaming it drops the lookup back to
    2008 just as silently. So the Annotate page and Settings both report this.

    `rows_2021`/`rows_2008` are counted per row, not inferred from the file:
    a 2021 build folds in every 2008 row that 2021 does not appear to cover
    (see scripts/build_gi_data.py), so the local table is a genuine mixture
    and the split is worth showing.
    """
    path = active_table_path()
    if path is None:
        return {"path": None, "is_local": False, "edition": None, "built": None,
                "rows": 0, "rows_2021": 0, "rows_2008": 0,
                "normal": 0, "impaired": 0, "unknown": 0}
    data = _data()
    rows = [row for pool in data.values() for row in pool]
    try:
        built = datetime.date.fromtimestamp(path.stat().st_mtime).isoformat()
    except OSError:
        built = None
    return {
        "path":       str(path),
        "is_local":   path.name == _LOCAL_NAME,
        "edition":    2021 if path.name == _LOCAL_NAME else 2008,
        "built":      built,
        "rows":       len(rows),
        "rows_2021":  sum(1 for row in rows if row.get("edition") == 2021),
        "rows_2008":  sum(1 for row in rows if row.get("edition") != 2021),
        "normal":     len(data.get("normal", [])),
        "impaired":   len(data.get("impaired", [])),
        "unknown":    len(data.get("unknown", [])),
    }


def _data() -> dict[str, list[dict]]:
    global _data_cache
    if _data_cache is None:
        path = active_table_path()
        if path is not None:
            _data_cache = json.loads(path.read_text(encoding="utf-8"))
            _data_cache.setdefault("unknown", [])
        else:
            _data_cache = {"normal": [], "impaired": [], "unknown": []}
    return _data_cache


def _normalize(name: str) -> str:
    name = name.lower()
    name = re.sub(r"[^a-z0-9]+", " ", name)
    return re.sub(r"\s+", " ", name).strip()


def _score(query_norm: str, entry_norm: str) -> float:
    if not query_norm or not entry_norm:
        return 0.0
    if query_norm == entry_norm:
        return 1.0
    if query_norm in entry_norm or entry_norm in query_norm:
        return 0.9
    return difflib.SequenceMatcher(None, query_norm, entry_norm).ratio()


def search(query: str, population: str = "both", limit: int = 8, cutoff: float = 0.5) -> list[dict]:
    """Return up to `limit` candidate table entries for `query`, ranked by
    name-match quality (best first). `population` is "normal", "impaired",
    or "both".

    Each result: {name, gi_glucose, sem, year, country, population,
    subjects_type, subjects_n, category, subcategory, iso, edition, ref,
    food_number, score}; `year`, `sem`, `country` and `iso` are None on rows
    carried over from the 2008 edition. [] if the data file hasn't been
    generated yet (see scripts/build_gi_data.py) or nothing scored above
    `cutoff`.

    Asking for one population also returns the rows whose subject group the
    source left unstated. Withholding them from both lists would hide real
    values from whichever population the user picked, and each result shows
    its own subject group, so an unstated one is visible as such."""
    query_norm = _normalize(query)
    if not query_norm:
        return []

    data = _data()
    if population == "both":
        pools = [data.get("normal", []), data.get("impaired", []),
                 data.get("unknown", [])]
    else:
        pools = [data.get(population, []), data.get("unknown", [])]

    scored = []
    for pool in pools:
        for entry in pool:
            s = _score(query_norm, _normalize(entry["name"]))
            if s >= cutoff:
                scored.append({**entry, "score": s})

    scored.sort(key=lambda e: e["score"], reverse=True)
    return scored[:limit]
