"""
demo_data.py — starter foods/pantry/recipes, auto-loaded on a fresh install
and also available as an optional Settings toggle thereafter.
Docs: README-numa-documentation.md, Project Structure

The actual content lives in starter_data.json, next to this file — not in
Python code. It's regenerated by scripts/export_starter_data.py, which pulls
every food/pantry/recipe in a real database whose name starts with "* ".
That means curating starter content is done the normal way, in the app
itself (rename or create a food/recipe with a leading "* "), not by editing
this module. Run the export script before cutting a release to pick up any
curation changes.

Names are prefixed "* " so they stay visually distinct from anything the
user adds themselves, in Food Cache/Pantry/Recipes listings and search.
seed_if_fresh_install() populates them automatically the first time the app
opens an empty database (a true fresh install); the existing Settings
load/clear toggle (settings_demo_data_load/clear in web/backend.py) uses the
same load_demo_data()/clear_demo_data() for anyone who cleared it and wants
it back.
"""
import json
import pathlib
import sys

import db as _db
import platform_utils as _platform_utils
from numa_app.services import recipe_dcp as _recipe_dcp

_MARKER_FILE = _platform_utils.get_data_dir() / "demo_data.json"
# Separate from _MARKER_FILE: this one records that the one-time fresh-install
# auto-seed was attempted, and is never removed by clear_demo_data() — so
# clearing starter data on a DB that has nothing else in it doesn't make the
# next app start look like a fresh install again and reseed it.
_SEED_ATTEMPTED_MARKER = _platform_utils.get_data_dir() / "demo_data_seed_attempted"

# In a PyInstaller onefile build, this module is imported from inside the
# zipped bundle, so a __file__-relative path doesn't exist on disk — datas
# get extracted under sys._MEIPASS instead (same pattern web/backend.py uses
# for templates/static/oxalate.db). See nutrimagnus.spec's datas list, which
# bundles this file at numa_app/services/starter_data.json.
if getattr(sys, "frozen", False):
    _STARTER_DATA_FILE = pathlib.Path(sys._MEIPASS) / "numa_app" / "services" / "starter_data.json"
else:
    _STARTER_DATA_FILE = pathlib.Path(__file__).parent / "starter_data.json"
_starter = json.loads(_STARTER_DATA_FILE.read_text())
DEMO_FOODS: list[dict] = _starter["foods"]
DEMO_PANTRY: list[str] = _starter["pantry"]
DEMO_RECIPES: list[dict] = _starter["recipes"]


def _ingredient_parts(entry) -> tuple[str, float, str, str]:
    """(name, amount, unit, kind) for one starter-recipe ingredient entry.

    Entries are [name, amount, unit, kind], where kind is "food" or "recipe"
    (a sub-recipe, whose name is another starter recipe). A 3-element entry
    predates nested-recipe support and is always a food."""
    return entry[0], entry[1], entry[2], (entry[3] if len(entry) > 3 else "food")


def _add_ingredients(conn, recipe_id: int, recipe: dict, by_name: dict, recipe_ids: dict) -> None:
    """Attach one starter recipe's ingredients, foods and sub-recipes alike.

    A sub-recipe row carries fdc_id 0 and a ref_recipe_id, exactly as the app
    writes one. starter_data.json lists every recipe after the ones it uses,
    so recipe_ids already holds the id a sub-recipe was created with."""
    for name, amount, unit, kind in (_ingredient_parts(i) for i in recipe["ingredients"]):
        if kind == "recipe":
            _db.recipe_add_ingredient(conn, recipe_id, 0, name, amount, unit,
                                      ref_recipe_id=recipe_ids[name])
        else:
            _db.recipe_add_ingredient(conn, recipe_id, by_name[name]["fdc_id"], name, amount, unit)


def is_loaded() -> bool:
    """True if load_demo_data() has been run and not yet cleared."""
    return _MARKER_FILE.exists()


def _is_fresh_install(conn) -> bool:
    """True if the database has no foods, pantry, or recipes at all — the
    signal that this is a brand-new install, not a returning user's DB."""
    row = conn.execute(
        "SELECT (SELECT COUNT(*) FROM foods) + (SELECT COUNT(*) FROM pantry) "
        "+ (SELECT COUNT(*) FROM recipes) AS n"
    ).fetchone()
    return row["n"] == 0


def seed_if_fresh_install(conn) -> dict:
    """Auto-load the starter foods/pantry/recipes exactly once, the first
    time the app ever opens a completely empty database. Guarded by
    _SEED_ATTEMPTED_MARKER (not is_loaded()) so that clearing starter data
    from Settings — which can leave the DB empty again if nothing else was
    added — never causes a later app start to mistake that for a fresh
    install and reseed it."""
    if _SEED_ATTEMPTED_MARKER.exists() or not _is_fresh_install(conn):
        return {"foods": 0, "pantry": 0, "recipes": 0, "skipped": True}
    _SEED_ATTEMPTED_MARKER.parent.mkdir(parents=True, exist_ok=True)
    _SEED_ATTEMPTED_MARKER.write_text("")
    return load_demo_data(conn)


def load_demo_data(conn) -> dict:
    """Insert the sample foods/pantry/recipes, tracking exactly what was
    inserted in a marker file so clear_demo_data() can remove precisely
    that later. No-op (returns zero counts) if already loaded."""
    if is_loaded():
        return {"foods": 0, "pantry": 0, "recipes": 0, "already_loaded": True}

    fdc_ids: list[int] = []
    for food in DEMO_FOODS:
        _db.cache_food(
            conn, food["fdc_id"], food["name"], food["data_type"],
            None, None, None, food["nutrients"], food["portions"],
            user_drafted=True, notes="Starter data",
        )
        fdc_ids.append(food["fdc_id"])

    by_name = {f["name"]: f for f in DEMO_FOODS}
    pantry_ids: list[int] = []
    for name in DEMO_PANTRY:
        pantry_ids.append(_db.pantry_add(conn, name, by_name[name]["fdc_id"], "Starter data"))

    recipe_ids: list[int] = []
    rid_by_name: dict[str, int] = {}
    for recipe in DEMO_RECIPES:
        rid = _db.recipe_create(
            conn, name=recipe["name"], description=recipe["description"],
            servings=recipe["servings"], instructions=recipe["instructions"],
            complete=True,
        )
        rid_by_name[recipe["name"]] = rid
        _add_ingredients(conn, rid, recipe, by_name, rid_by_name)
        _recipe_dcp.recompute_recipe_dcp(rid, conn)
        recipe_ids.append(rid)

    _MARKER_FILE.parent.mkdir(parents=True, exist_ok=True)
    _MARKER_FILE.write_text(json.dumps({
        "fdc_ids": fdc_ids, "pantry_ids": pantry_ids, "recipe_ids": recipe_ids,
    }))

    return {"foods": len(fdc_ids), "pantry": len(pantry_ids), "recipes": len(recipe_ids)}


def clear_demo_data(conn) -> dict:
    """Remove exactly what load_demo_data() inserted, per the marker file.
    No-op (returns zero counts) if nothing is loaded.

    A starter food the user has since used somewhere of their own — logged in a
    meal, added to a recipe, kept in the pantry — is left in place and counted
    in "foods_kept". Deleting it would strand that reference (and the database
    now refuses outright, via trg_foods_no_delete_when_referenced), so the
    choice is between keeping one food and failing the whole clear."""
    if not is_loaded():
        return {"foods": 0, "pantry": 0, "recipes": 0, "foods_kept": 0}

    marker = json.loads(_MARKER_FILE.read_text())
    fdc_ids = marker.get("fdc_ids", [])
    pantry_ids = marker.get("pantry_ids", [])
    recipe_ids = marker.get("recipe_ids", [])

    # Reverse order: starter recipes are created sub-recipe-first, so a
    # sub-recipe still has a parent pointing at it until that parent is gone
    # (recipe_ingredients.ref_recipe_id is a foreign key onto recipes.id).
    for rid in reversed(recipe_ids):
        conn.execute("DELETE FROM recipes WHERE id = ?", (rid,))  # cascades to recipe_ingredients
    for pid in pantry_ids:
        conn.execute("DELETE FROM pantry WHERE id = ?", (pid,))
    # After the starter recipes and pantry entries above are gone, whatever
    # still references a starter food belongs to the user.
    deleted_foods = 0
    kept_foods = 0
    for fdc_id in fdc_ids:
        refs = _db.food_references(conn, fdc_id)
        if refs["pantry"] or refs["recipes"] or refs["meals"]:
            kept_foods += 1
            continue
        conn.execute("DELETE FROM foods WHERE fdc_id = ?", (fdc_id,))
        deleted_foods += 1

    _MARKER_FILE.unlink()

    return {"foods": deleted_foods, "pantry": len(pantry_ids), "recipes": len(recipe_ids),
            "foods_kept": kept_foods}


def starter_status(conn) -> dict:
    """Per-item presence of every starter food/pantry item/recipe in the
    current DB, for the Settings selective-restore checkbox list. Checked
    against the DB directly (not the load/clear marker file) so it stays
    accurate even after a selective restore or a manual edit/delete of a
    starter item."""
    cached_ids = {row["fdc_id"] for row in conn.execute("SELECT fdc_id FROM foods").fetchall()}
    pantry_pairs = {(row["food_name"], row["fdc_id"]) for row in _db.pantry_list(conn, include_archived=True)}
    recipe_names = {row["name"] for row in _db.recipe_list(conn, include_archived=True)}

    by_name = {f["name"]: f for f in DEMO_FOODS}
    return {
        "foods": [
            {"fdc_id": f["fdc_id"], "name": f["name"], "present": f["fdc_id"] in cached_ids}
            for f in DEMO_FOODS
        ],
        "pantry": [
            {"name": name, "present": (name, by_name[name]["fdc_id"]) in pantry_pairs}
            for name in DEMO_PANTRY
        ],
        "recipes": [
            {"name": r["name"], "present": r["name"] in recipe_names}
            for r in DEMO_RECIPES
        ],
    }


def restore_selected(conn, food_fdc_ids: list[int], pantry_names: list[str], recipe_names: list[str]) -> dict:
    """Add back specific starter foods/pantry items/recipes that aren't
    already present, alongside (not replacing) the all-or-nothing
    load_demo_data()/clear_demo_data(). Selecting a pantry item or recipe
    auto-includes any starter food it depends on that isn't already cached,
    since a pantry item or recipe ingredient can't exist without its food.
    A selected recipe likewise pulls in any sub-recipe it uses, and their
    sub-recipes in turn, for the same reason — an ingredient row pointing at
    a recipe that isn't there is a broken reference.
    Items already present are skipped, so this is safe to call repeatedly
    with an overlapping selection."""
    by_name = {f["name"]: f for f in DEMO_FOODS}
    by_fdc_id = {f["fdc_id"]: f for f in DEMO_FOODS}
    cached_ids = {row["fdc_id"] for row in conn.execute("SELECT fdc_id FROM foods").fetchall()}

    # Widen the selection to every sub-recipe reachable from it, then keep
    # DEMO_RECIPES order, in which a sub-recipe always precedes its user.
    recipes_by_name = {r["name"]: r for r in DEMO_RECIPES}
    wanted_recipes = set(recipe_names)
    pending = list(wanted_recipes)
    while pending:
        recipe = recipes_by_name.get(pending.pop())
        if recipe is None:
            continue
        for name, _amount, _unit, kind in (_ingredient_parts(i) for i in recipe["ingredients"]):
            if kind == "recipe" and name not in wanted_recipes:
                wanted_recipes.add(name)
                pending.append(name)
    recipe_defs = [r for r in DEMO_RECIPES if r["name"] in wanted_recipes]
    needed_fdc_ids = set(food_fdc_ids) | {by_name[name]["fdc_id"] for name in pantry_names}
    for recipe in recipe_defs:
        needed_fdc_ids |= {
            by_name[name]["fdc_id"]
            for name, _amount, _unit, kind in (_ingredient_parts(i) for i in recipe["ingredients"])
            if kind == "food"
        }

    added_foods = 0
    for fdc_id in needed_fdc_ids:
        if fdc_id in cached_ids:
            continue
        food = by_fdc_id[fdc_id]
        _db.cache_food(
            conn, food["fdc_id"], food["name"], food["data_type"],
            None, None, None, food["nutrients"], food["portions"],
            user_drafted=True, notes="Starter data",
        )
        cached_ids.add(fdc_id)
        added_foods += 1

    existing_pantry = {(row["food_name"], row["fdc_id"]) for row in _db.pantry_list(conn, include_archived=True)}
    added_pantry = 0
    for name in pantry_names:
        fdc_id = by_name[name]["fdc_id"]
        if (name, fdc_id) in existing_pantry:
            continue
        _db.pantry_add(conn, name, fdc_id, "Starter data")
        added_pantry += 1

    # Name -> id for every recipe already in the DB, so a parent recipe links
    # to a sub-recipe that is already there rather than duplicating it.
    rid_by_name = {row["name"]: row["id"] for row in _db.recipe_list(conn, include_archived=True)}
    added_recipes = 0
    for recipe in recipe_defs:
        if recipe["name"] in rid_by_name:
            continue
        rid = _db.recipe_create(
            conn, name=recipe["name"], description=recipe["description"],
            servings=recipe["servings"], instructions=recipe["instructions"],
            complete=True,
        )
        rid_by_name[recipe["name"]] = rid
        _add_ingredients(conn, rid, recipe, by_name, rid_by_name)
        _recipe_dcp.recompute_recipe_dcp(rid, conn)
        added_recipes += 1

    return {"foods": added_foods, "pantry": added_pantry, "recipes": added_recipes}
